# Generated by Django 3.2.4 on 2024-07-17 17:29

import admin_panel.liveconfigs.models.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRow',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=admin_panel.liveconfigs.models.models.CustomJSONEncoder, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None)),
                ('last_read', models.DateTimeField(blank=True, null=True)),
                ('last_set', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
