# Generated by Django 4.2 on 2025-09-14 12:36

import admin_panel.liveconfigs.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveconfigs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configrow",
            name="value",
            field=models.JSONField(
                blank=True,
                encoder=admin_panel.liveconfigs.models.models.CustomJSONEncoder,
                null=True,
            ),
        ),
    ]
