# Generated by Django 4.2 on 2025-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username клиента",
                        max_length=50,
                        null=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="Telegram ID пользователя", verbose_name="Telegram ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя в Telegram",
                        max_length=255,
                        verbose_name="Имя в Telegram",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=255, verbose_name="Ссылка на пользователя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиенты телеграмм бота",
                "verbose_name_plural": "Клиенты телеграмм бота",
                "ordering": ("-created",),
            },
        ),
    ]
