# Generated by Django 4.2 on 2025-08-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telebot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="balance",
            field=models.IntegerField(
                default=0, help_text="Баланс клиента", verbose_name="Баланс"
            ),
        ),
        migrations.CreateModel(
            name="VideoGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="File ID сгенерированного видео",
                        max_length=255,
                        verbose_name="File ID видео",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("failed", "Не удалось"),
                        ],
                        help_text="Статус генерации видео",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_generation",
                        to="telebot.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Генерация видео",
                "verbose_name_plural": "Генерации видео",
                "ordering": ("-created",),
            },
        ),
    ]
