# Generated by Django 4.2 on 2025-08-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telebot", "0002_client_balance_videogeneration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogeneration",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе"),
                    ("completed", "Завершено"),
                    ("failed", "Не удалось"),
                ],
                default="in_progress",
                help_text="Статус генерации видео",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
