# Generated by Django 4.2 on 2025-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telebot", "0003_alter_videogeneration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogeneration",
            name="message_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID сообщения с видео в телеграм",
                null=True,
                verbose_name="Message ID",
            ),
        ),
    ]
