# Generated by Django 4.2 on 2025-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telebot", "0005_videogeneration_result_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogeneration",
            name="failed_message",
            field=models.TextField(
                blank=True,
                help_text="Сообщение об ошибке при генерации видео",
                null=True,
                verbose_name="Сообщение об ошибке",
            ),
        ),
    ]
