# Generated by Django 4.2 on 2025-08-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telebot", "0006_videogeneration_failed_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="free_chat_daily_limit",
            field=models.IntegerField(
                default=10, verbose_name="Лимит бесплатных ChatGPT сообщений в день"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="free_chat_last_reset",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего сброса лимита"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="free_chat_used_today",
            field=models.IntegerField(
                default=0, verbose_name="Использовано сегодня (ChatGPT)"
            ),
        ),
    ]
